---
- fail:
    msg: 'This ansible role supports Debian and Ubuntu 14+ only'
  when: (ansible_distribution not in ['Debian', 'Ubuntu']) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int < 14)

- include_vars: debian.yml
  when: ansible_distribution == 'Debian'

- include_vars: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'


- include: install.yml
  tags: ['php5-fpm-install']

- include: configure.yml
  tags: ['php5-fpm-configure']

- include: modules.yml
  tags: ['php5-fpm-modules']

- include: pools.yml
  tags: ['php5-fpm-pools']

- name: Start php5-fpm
  service:
    name: 'php5-fpm'
    state: started
    enabled: yes
  changed_when: false # required for idempotence