---
- fail:
    msg: 'This ansible role supports Debian and Ubuntu 14+ only'
  when: (ansible_distribution not in ['Debian', 'Ubuntu']) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int < 14)

- include_vars: debian.yml
  when: ansible_distribution == 'Debian'

- include_vars: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'


- include: install.yml
- include: configure.yml
- include: modules.yml
- include: pools.yml

- name: Ensure php-fpm is started and enabled at boot.
  service:
    name: php5-fpm
    state: started
    enabled: yes
